// <auto-generated />
using System;
using EmployeeWorkTracker_Test.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeWorkTracker_Test.Migrations
{
    [DbContext(typeof(EmployeeWorkingHoursContext))]
    partial class WorkingHoursContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeWorkTracker_Test.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2024, 4, 28, 22, 25, 16, 957, DateTimeKind.Local).AddTicks(2281),
                            FirstName = "Tomislav",
                            LastName = "Marinković",
                            LastUpdate = new DateTime(2024, 4, 28, 22, 25, 16, 957, DateTimeKind.Local).AddTicks(2335)
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2024, 4, 25, 22, 25, 16, 957, DateTimeKind.Local).AddTicks(2338),
                            FirstName = "Marina",
                            LastName = "Perović",
                            LastUpdate = new DateTime(2024, 4, 28, 22, 25, 16, 957, DateTimeKind.Local).AddTicks(2342)
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2024, 4, 24, 23, 25, 16, 957, DateTimeKind.Local).AddTicks(2344),
                            FirstName = "Petra",
                            LastName = "Božinović",
                            LastUpdate = new DateTime(2024, 4, 28, 22, 25, 16, 957, DateTimeKind.Local).AddTicks(2347)
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2024, 4, 20, 19, 25, 16, 957, DateTimeKind.Local).AddTicks(2349),
                            FirstName = "Mario",
                            LastName = "Došen",
                            LastUpdate = new DateTime(2024, 4, 28, 22, 25, 16, 957, DateTimeKind.Local).AddTicks(2351)
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2024, 4, 21, 15, 25, 16, 957, DateTimeKind.Local).AddTicks(2354),
                            FirstName = "Ozren",
                            LastName = "Bogdan",
                            LastUpdate = new DateTime(2024, 4, 28, 22, 25, 16, 957, DateTimeKind.Local).AddTicks(2355)
                        });
                });

            modelBuilder.Entity("EmployeeWorkTracker_Test.Models.WorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("EmployeeWorkTracker_Test.Models.WorkingHours", b =>
                {
                    b.HasOne("EmployeeWorkTracker_Test.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
